version: "3.8"

services:
 
    db:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - '1433:1433'
        environment:
            - 'ACCEPT_EULA=Y'
            - "SA_PASSWORD=yourStrongPassword12!@"
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - petfoodshop-network

    messaging:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports: 
            - '15672:15672'
            - '5672:5672'
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks: 
            - petfoodshop-network

    identity:
        container_name: identity
        build:
            context: ./server
            dockerfile: ./Identity/Identity.Startup/dev.Dockerfile
        ports: 
            - "5002:80"
        env_file: server/Common/Common.Infrastructure/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetShopDB-Identity;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - petfoodshop-network
        depends_on:
            - db

    admin:
        container_name: admin
        build:
            context: ./server
            dockerfile: ./Admin/Admin.Startup/dev.Dockerfile
        ports: 
            - "5008:80"
        env_file: server/Common/Common.Infrastructure/Common.env
        environment:
            - ServiceEndpoints__Identity=http://identity
            - ServiceEndpoints__Statistics=http://statistics
            - ServiceEndpoints__Foods=http://foods
            - ServiceEndpoints__FoodCategories=http://foods
        restart: on-failure
        volumes:
            - ./.aspnet/admin/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - petfoodshop-network

    cart:
        container_name: cart
        build:
            context: ./server
            dockerfile: ./Cart/Cart.Startup/dev.Dockerfile
        ports: 
            - "5014:80"
        env_file: server/Common/Common.Infrastructure/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetShopDB-Cart;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmq
            - MessageQueueSettings__Password=rabbitmq
        restart: on-failure
        volumes:
            - ./.aspnet/cart/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - petfoodshop-network
        depends_on:
            - db

    foods:
        container_name: foods
        build:
            context: ./server
            dockerfile: ./Foods/Foods.Startup/dev.Dockerfile
        ports: 
            - "5000:80"
        env_file: server/Common/Common.Infrastructure/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetShopDB-Foods;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmq
            - MessageQueueSettings__Password=rabbitmq
        restart: on-failure
        volumes:
            - ./.aspnet/foods/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - petfoodshop-network
        depends_on:
            - db

    foodsgateway:
        container_name: foodsgateway 
        build:
            context: ./server
            dockerfile: ./Gateway/Gateway.Startup/dev.Dockerfile
        ports: 
            - "5010:80"
        env_file: server/Common/Common.Infrastructure/Common.env
        restart: on-failure
        volumes:
            - ./.aspnet/foodsgateway/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - petfoodshop-network
        depends_on:
            - foods

    notifications:
        container_name: notifications
        build:
            context: ./server
            dockerfile: ./Notifications/Notifications.Startup/dev.Dockerfile
        ports: 
            - "5012:80"
        env_file: server/Common/Common.Infrastructure/Common.env
        environment: 
            - NotificationSettings__AllowedOrigins=http://localhost
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmq
            - MessageQueueSettings__Password=rabbitmq
        restart: on-failure
        volumes:
            - ./.aspnet/notifications/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - petfoodshop-network

    statistics:
        container_name: statistics
        build:
            context: ./server
            dockerfile: ./Statistics/Statistics.Startup/dev.Dockerfile
        ports: 
            - "5006:80"
        env_file: server/Common/Common.Infrastructure/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetShopDB-Statistics;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmq
            - MessageQueueSettings__Password=rabbitmq
        restart: on-failure
        volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - petfoodshop-network
        depends_on:
            - db
    watchdog:
        container_name: watchdog
        build:
            context: ./server
            dockerfile: ./Watchdog/Watchdog.Startup/dev.Dockerfile
        ports:
            - "5500:80"
        environment:
            - HealthChecks-UI__HealthChecks__0__Name=Identity
            - HealthChecks-UI__HealthChecks__0__Uri=http://identity/health
            - HealthChecks-UI__HealthChecks__1__Name=Cart
            - HealthChecks-UI__HealthChecks__1__Uri=http://cart/health
            - HealthChecks-UI__HealthChecks__2__Name=Foods
            - HealthChecks-UI__HealthChecks__2__Uri=http://foods/health
            - HealthChecks-UI__HealthChecks__3__Name=Statistics
            - HealthChecks-UI__HealthChecks__3__Uri=http://statistics/health
            - HealthChecks-UI__HealthChecks__4__Name=Notifications
            - HealthChecks-UI__HealthChecks__4__Uri=http://notifications/health
            - HealthChecks-UI__HealthChecks__5__Name=Admin
            - HealthChecks-UI__HealthChecks__5__Uri=http://admin/health
        restart: on-failure
        networks: 
            - petfoodshop-network
        depends_on:
            - identity
            - cart
            - foods
            - statistics
            - notifications
            - admin
    client:
        container_name: client
        build:
             context: ./client
             dockerfile: ./Dockerfile
             args:
                configuration: development
        ports:
          - "80:80"
        networks: 
            - petfoodshop-network
        depends_on:
            - identity
            - cart
            - notifications
            - foodsgateway
        volumes:
         - ./.aspnet/client/
         - ./node_modules

networks: 
    petfoodshop-network:
        driver: bridge

volumes: 
    sqldata: